"use client";

import { Archive, ChevronRight, Copy, FileText, MoreHorizontal, Plus, Search, Share2, Star, Trash2, UserPlus } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useMemo, useState, useTransition } from "react";
import { createPage, duplicatePage, duplicateSpace, inviteSpaceMember, movePage, permanentlyDeletePage, permanentlyDeleteSpace, removeSpaceMember, setPageArchived, setPageFavorite, setSpaceArchived, updateSpace } from "../actions";
import { Avatar, colors, Empty, fieldClass, Modal, relativeTime } from "../spaces-ui";
import { pageTemplates, templateLabels, type PageTemplate } from "@/lib/page-templates";

type Space = { id:number; name:string; description:string|null; color:string; archivedAt:string|null; createdAt:string; updatedAt:string; isOwner:boolean };
type Page = { id:number; spaceId:number; name:string; description:string|null; template:string; archivedAt:string|null; createdAt:string; updatedAt:string; updatedBy:string; isFavorite:boolean; updatedByUser:{name:string|null;email:string;avatarUrl:string|null}|null };
type Collaborator = { email:string; name:string|null; avatarUrl:string|null; role:string };

export function SpaceWorkspace({ space, pages, collaborators, availableSpaces, shareOpen=false }: { space:Space; pages:Page[]; collaborators:Collaborator[]; availableSpaces:{id:number;name:string;archived:boolean}[]; shareOpen?:boolean }) {
  const router=useRouter(); const [search,setSearch]=useState(""); const [archived,setArchived]=useState(false); const [dialog,setDialog]=useState<"page"|"share"|"edit"|null>(shareOpen?"share":null); const [menu,setMenu]=useState<number|null>(null); const [message,setMessage]=useState(""); const [pending,startTransition]=useTransition();
  const run=(action:()=>Promise<unknown>, success:string, after?:(value:unknown)=>void)=>startTransition(async()=>{try{const result=await action();setMessage(success);setMenu(null);setDialog(null);after?.(result);router.refresh();}catch(error){setMessage(error instanceof Error?error.message:"Something went wrong.");}});
  const visible=useMemo(()=>pages.filter((page)=>Boolean(page.archivedAt)===archived&&page.name.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)),[pages,archived,search]);
  return <div className="mx-auto min-h-screen w-full max-w-[1600px] p-4 sm:p-7">{message&&<button onClick={()=>setMessage("")} className="fixed bottom-5 right-5 z-[100] rounded-xl bg-stone-900 px-4 py-3 text-sm text-white shadow-xl">{message}</button>}
    <div className="flex items-center gap-1 text-sm text-stone-500"><Link href="/spaces" className="hover:text-violet-700">All Spaces</Link><ChevronRight className="h-4 w-4"/><span>{space.name}</span></div>
    <header className="mt-4 flex flex-col gap-4 rounded-2xl border border-violet-100 bg-white p-5 shadow-sm md:flex-row md:items-center md:justify-between"><div className="flex min-w-0 gap-3"><span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl" style={{backgroundColor:`${space.color}18`,color:space.color}}><FileText className="h-6 w-6"/></span><div className="min-w-0"><h1 className="truncate text-3xl font-semibold">{space.name}</h1><p className="mt-1 text-sm text-stone-500">{pages.filter((page)=>!page.archivedAt).length} pages · {space.description||"No description yet."}</p></div></div><div className="flex gap-2"><button onClick={()=>setDialog("share")} className="flex h-11 items-center gap-2 rounded-xl border border-stone-200 px-4 text-sm font-semibold"><Share2 className="h-4 w-4"/>Collaborators</button>{!space.archivedAt&&<button onClick={()=>setDialog("page")} className="flex h-11 items-center gap-2 rounded-xl bg-violet-600 px-4 text-sm font-semibold text-white"><Plus className="h-4 w-4"/>New Page</button>}<button onClick={()=>setMenu(menu===-1?null:-1)} className="rounded-xl border border-stone-200 px-3"><MoreHorizontal className="h-4 w-4"/></button></div>{menu===-1&&<div className="absolute right-8 top-28 z-30 w-52 rounded-xl border bg-white p-1.5 text-sm shadow-xl">{space.isOwner&&<><Menu label="Rename / change color" onClick={()=>setDialog("edit")}/><Menu label="Duplicate Space" onClick={()=>run(()=>duplicateSpace(space.id),"Space duplicated.",(id)=>router.push(`/spaces/${id}`))}/>{space.archivedAt?<><Menu label="Restore Space" onClick={()=>run(()=>setSpaceArchived(space.id,false),"Space restored.")}/><Menu danger label="Delete permanently" onClick={()=>window.confirm(`Permanently delete "${space.name}"?`)&&run(()=>permanentlyDeleteSpace(space.id),"Space deleted.",()=>router.push("/spaces"))}/></>:<Menu label="Archive Space" onClick={()=>run(()=>setSpaceArchived(space.id,true),"Space archived.",()=>router.push("/spaces"))}/>}</>}</div>}</header>
    <section className="mt-5 rounded-2xl border border-stone-200 bg-white p-4 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row"><label className="flex h-11 flex-1 items-center gap-2 rounded-xl border border-stone-200 px-3 text-stone-400"><Search className="h-4 w-4"/><input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Search pages…" className="flex-1 outline-none"/></label><button onClick={()=>setArchived(false)} className={`rounded-xl px-4 text-sm font-medium ${!archived?"bg-violet-100 text-violet-700":"bg-stone-50"}`}>Pages</button><button onClick={()=>setArchived(true)} className={`rounded-xl px-4 text-sm font-medium ${archived?"bg-violet-100 text-violet-700":"bg-stone-50"}`}>Archived</button></div></section>
    <section className="mt-5 overflow-visible rounded-2xl border border-stone-200 bg-white shadow-sm"><div className="hidden rounded-t-2xl grid-cols-[minmax(0,1fr)_180px_150px_160px_70px] gap-3 border-b bg-stone-50 px-5 py-3 text-xs font-semibold uppercase text-stone-500 md:grid"><span>Page Name</span><span>Type / Template</span><span>Last Updated</span><span>Updated By</span><span></span></div>{visible.map((page)=><div key={page.id} className="relative grid gap-3 border-b border-stone-100 px-5 py-4 last:border-0 md:grid-cols-[minmax(0,1fr)_180px_150px_160px_70px] md:items-center"><Link href={`/spaces/${space.id}/pages/${page.id}`} className="flex min-w-0 items-center gap-3 font-medium hover:text-violet-700"><FileText className="h-5 w-5 shrink-0" style={{color:space.color}}/><span className="truncate">{page.name}</span></Link><span className="w-fit rounded-lg bg-violet-50 px-2 py-1 text-xs font-medium text-violet-700">{templateLabels[page.template as PageTemplate]||page.template}</span><span className="text-sm text-stone-500">{relativeTime(page.updatedAt)}</span><span className="flex items-center gap-2 text-sm text-stone-600">{page.updatedByUser&&<Avatar person={page.updatedByUser}/>}<span className="truncate">{page.updatedByUser?.name||"Unknown"}</span></span><span className="flex"><button onClick={()=>run(()=>setPageFavorite(page.id,!page.isFavorite),page.isFavorite?"Removed from favorites.":"Added to favorites.")} className="rounded-lg p-2"><Star className={`h-4 w-4 ${page.isFavorite?"fill-amber-400 text-amber-400":"text-stone-400"}`}/></button><button onClick={()=>setMenu(menu===page.id?null:page.id)} className="rounded-lg p-2"><MoreHorizontal className="h-4 w-4"/></button></span>{menu===page.id&&<div className="absolute right-5 top-14 z-20 w-52 rounded-xl border bg-white p-1.5 text-sm shadow-xl"><Menu label="Open Page" onClick={()=>router.push(`/spaces/${space.id}/pages/${page.id}`)}/><Menu label="Duplicate" onClick={()=>run(()=>duplicatePage(page.id),"Page duplicated.")}/>{!page.archivedAt&&availableSpaces.filter((item)=>item.id!==space.id&&!item.archived).map((item)=><Menu key={item.id} label={`Move to ${item.name}`} onClick={()=>run(()=>movePage(page.id,item.id),"Page moved.")}/>)}{page.archivedAt?<><Menu label="Restore" onClick={()=>run(()=>setPageArchived(page.id,false),"Page restored.")}/><Menu danger label="Delete permanently" onClick={()=>window.confirm(`Permanently delete "${page.name}"?`)&&run(()=>permanentlyDeletePage(page.id),"Page deleted.")}/></>:<Menu label="Archive" onClick={()=>run(()=>setPageArchived(page.id,true),"Page archived.")}/>}</div>}</div>)}{!visible.length&&<div className="p-5"><Empty title={archived?"No archived pages":"Create your first page"} detail={archived?"Archived pages will appear here.":"Add a document to this space to get started."}/></div>}</section>
    {dialog==="page"&&<PageDialog currentSpaceId={space.id} spaces={availableSpaces} pending={pending} onClose={()=>setDialog(null)} onSubmit={(targetSpaceId,input)=>run(()=>createPage(targetSpaceId,input),"Page created.",(id)=>router.push(`/spaces/${targetSpaceId}/pages/${id}`))}/>}
    {dialog==="share"&&<ShareDialog collaborators={collaborators} owner={space.isOwner} pending={pending} onClose={()=>setDialog(null)} onInvite={(email)=>run(()=>inviteSpaceMember(space.id,email),"Collaborator invited.")} onRemove={(email)=>run(()=>removeSpaceMember(space.id,email),"Collaborator removed.")}/>}
    {dialog==="edit"&&<EditDialog space={space} pending={pending} onClose={()=>setDialog(null)} onSubmit={(input)=>run(()=>updateSpace(space.id,input),"Space updated.")}/>}
  </div>;
}
function Menu({label,onClick,danger=false}:{label:string;onClick:()=>void;danger?:boolean}){return <button onClick={onClick} className={`block w-full rounded-lg px-3 py-2 text-left hover:bg-stone-50 ${danger?"text-rose-600":""}`}>{label}</button>}
function PageDialog({currentSpaceId,spaces,pending,onClose,onSubmit}:{currentSpaceId:number;spaces:{id:number;name:string;archived:boolean}[];pending:boolean;onClose:()=>void;onSubmit:(spaceId:number,input:{name:string;description:string;template:string})=>void}){const[name,setName]=useState("");const[description,setDescription]=useState("");const[template,setTemplate]=useState("blank");const[targetSpaceId,setTargetSpaceId]=useState(currentSpaceId);return <Modal title="Create New Page" onClose={onClose}><form onSubmit={(e)=>{e.preventDefault();onSubmit(targetSpaceId,{name,description,template})}} className="space-y-4"><label className="block text-sm font-medium">Page Name<input autoFocus value={name} maxLength={120} onChange={(e)=>setName(e.target.value)} className={"mt-2 "+fieldClass}/></label><label className="block text-sm font-medium">Add to Space<select value={targetSpaceId} onChange={(e)=>setTargetSpaceId(Number(e.target.value))} className={"mt-2 "+fieldClass}>{spaces.filter((item)=>!item.archived).map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="block text-sm font-medium">Description<textarea value={description} maxLength={1000} onChange={(e)=>setDescription(e.target.value)} className="mt-2 min-h-20 w-full rounded-xl border p-3"/></label><label className="block text-sm font-medium">Template<select value={template} onChange={(e)=>setTemplate(e.target.value)} className={"mt-2 "+fieldClass}>{pageTemplates.map((item)=><option key={item} value={item}>{templateLabels[item]}</option>)}</select></label><button disabled={pending} className="h-11 w-full rounded-xl bg-violet-600 font-semibold text-white disabled:opacity-50">Create Page</button></form></Modal>}
function ShareDialog({collaborators,owner,pending,onClose,onInvite,onRemove}:{collaborators:Collaborator[];owner:boolean;pending:boolean;onClose:()=>void;onInvite:(email:string)=>void;onRemove:(email:string)=>void}){const[email,setEmail]=useState("");return <Modal title="Space Collaborators" onClose={onClose}>{owner&&<form onSubmit={(e)=>{e.preventDefault();onInvite(email);setEmail("")}} className="mb-4 flex gap-2"><input value={email} onChange={(e)=>setEmail(e.target.value)} placeholder="name@example.com" className={fieldClass}/><button disabled={pending} className="rounded-xl bg-violet-600 px-3 text-white"><UserPlus className="h-4 w-4"/></button></form>}<div className="space-y-2">{collaborators.map((person)=><div key={person.email} className="flex items-center gap-3 rounded-xl border p-3"><Avatar person={person}/><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{person.name||person.email}</p><p className="truncate text-xs text-stone-500">{person.email} · {person.role}</p></div>{owner&&person.role!=="owner"&&<button onClick={()=>onRemove(person.email)} className="text-xs text-rose-600">Remove</button>}</div>)}</div></Modal>}
function EditDialog({space,pending,onClose,onSubmit}:{space:Space;pending:boolean;onClose:()=>void;onSubmit:(input:{name:string;description:string;color:string})=>void}){const[name,setName]=useState(space.name);const[description,setDescription]=useState(space.description||"");const[color,setColor]=useState(space.color);return <Modal title="Edit Space" onClose={onClose}><form onSubmit={(e)=>{e.preventDefault();onSubmit({name,description,color})}} className="space-y-4"><input value={name} onChange={(e)=>setName(e.target.value)} className={fieldClass}/><textarea value={description} onChange={(e)=>setDescription(e.target.value)} className="min-h-24 w-full rounded-xl border p-3"/><div className="flex gap-2">{colors.map((item)=><button type="button" key={item} onClick={()=>setColor(item)} className={`h-8 w-8 rounded-full ${color===item?"ring-2 ring-violet-500 ring-offset-2":""}`} style={{backgroundColor:item}}/>)}</div><button disabled={pending} className="h-11 w-full rounded-xl bg-violet-600 font-semibold text-white">Save Changes</button></form></Modal>}
