"use client";

import { Archive, Folder, Grid2X2, List, MoreHorizontal, Plus, Search, Star, Trash2 } from "lucide-react";
import { useRouter } from "next/navigation";
import { useEffect, useMemo, useState, useTransition } from "react";
import { createSpace, duplicateSpace, permanentlyDeleteSpace, recordSpaceOpen, setSpaceArchived, setSpaceFavorite, updateSpace } from "./actions";
import { Avatar, colors, Empty, fieldClass, Modal, relativeTime } from "./spaces-ui";

type Space = { id: number; name: string; description: string | null; color: string; archivedAt: string | null; createdAt: string; updatedAt: string; isOwner: boolean; isFavorite: boolean; openedAt: string | null; pageCount: number; pageNames: string[]; members: { name: string | null; email: string; avatarUrl: string | null }[] };

export function SpacesWorkspace({ spaces }: { spaces: Space[] }) {
  const router = useRouter();
  const [search, setSearch] = useState("");
  const [filter, setFilter] = useState("all");
  const [sort, setSort] = useState("updated");
  const [view, setView] = useState<"grid" | "list">("grid");
  const [dialog, setDialog] = useState<"create" | Space | null>(null);
  const [menu, setMenu] = useState<number | null>(null);
  const [message, setMessage] = useState("");
  const [pending, startTransition] = useTransition();
  useEffect(() => { setView(localStorage.getItem("spaces-view") === "list" ? "list" : "grid"); }, []);
  const run = (action: () => Promise<unknown>, success: string, after?: (value: unknown) => void) => startTransition(async () => { try { const result = await action(); setMessage(success); setMenu(null); setDialog(null); after?.(result); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Something went wrong."); } });
  const visible = useMemo(() => spaces.filter((space) => {
    const query = search.toLowerCase();
    const matches = !query || space.name.toLowerCase().includes(query) || (space.description || "").toLowerCase().includes(query) || space.pageNames.some((name) => name.toLowerCase().includes(query));
    if (!matches) return false;
    if (filter === "archived") return Boolean(space.archivedAt);
    if (space.archivedAt) return false;
    if (filter === "favorites") return space.isFavorite;
    if (filter === "recent") return Boolean(space.openedAt);
    return true;
  }).sort((a, b) => sort === "name" ? a.name.localeCompare(b.name) : sort === "pages" ? b.pageCount - a.pageCount : sort === "favorites" ? Number(b.isFavorite) - Number(a.isFavorite) : filter === "recent" ? (b.openedAt || "").localeCompare(a.openedAt || "") : b.updatedAt.localeCompare(a.updatedAt)), [spaces, search, filter, sort]);
  const open = (space: Space) => run(() => recordSpaceOpen(space.id), "", () => router.push(`/spaces/${space.id}`));
  return <div className="mx-auto min-h-screen w-full max-w-[1600px] p-4 sm:p-7">
    {message && <button onClick={() => setMessage("")} className="fixed bottom-5 right-5 z-[100] rounded-xl bg-stone-900 px-4 py-3 text-sm text-white shadow-xl">{message}</button>}
    <header className="flex flex-col gap-4 rounded-2xl border border-violet-100 bg-white p-5 shadow-sm md:flex-row md:items-center md:justify-between"><div><p className="text-xs font-semibold uppercase tracking-wide text-violet-600">Pages & Spaces</p><h1 className="mt-1 text-3xl font-semibold">All Spaces</h1><p className="mt-1 text-sm text-stone-500">{visible.length} {visible.length === 1 ? "space" : "spaces"}</p></div><button onClick={() => setDialog("create")} className="flex h-11 items-center justify-center gap-2 rounded-xl bg-violet-600 px-4 text-sm font-semibold text-white hover:bg-violet-700"><Plus className="h-4 w-4" />New Space</button></header>
    <section className="mt-5 rounded-2xl border border-stone-200 bg-white p-4 shadow-sm"><div className="flex flex-col gap-3 xl:flex-row xl:items-center"><label className="flex h-11 min-w-0 flex-1 items-center gap-2 rounded-xl border border-stone-200 px-3 text-stone-400"><Search className="h-4 w-4" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search spaces or pages…" className="min-w-0 flex-1 outline-none" /></label><div className="flex flex-wrap gap-2">{[["all","All Spaces"],["favorites","Favorites"],["recent","Recently Opened"],["archived","Archived"]].map(([id,label]) => <button key={id} onClick={() => setFilter(id)} className={`rounded-xl px-3 py-2 text-sm font-medium ${filter === id ? "bg-violet-100 text-violet-700" : "bg-stone-50 text-stone-600"}`}>{label}</button>)}</div><select value={sort} onChange={(event) => setSort(event.target.value)} className={fieldClass + " xl:w-48"}><option value="updated">Recently Updated</option><option value="name">Name</option><option value="pages">Most Pages</option><option value="favorites">Favorites</option></select><div className="flex rounded-xl border border-stone-200 p-1"><button aria-label="Grid view" onClick={() => { setView("grid"); localStorage.setItem("spaces-view","grid"); }} className={`rounded-lg p-2 ${view === "grid" ? "bg-violet-100 text-violet-700" : ""}`}><Grid2X2 className="h-4 w-4" /></button><button aria-label="List view" onClick={() => { setView("list"); localStorage.setItem("spaces-view","list"); }} className={`rounded-lg p-2 ${view === "list" ? "bg-violet-100 text-violet-700" : ""}`}><List className="h-4 w-4" /></button></div></div></section>
    <section className={`mt-5 ${view === "grid" ? "grid gap-4 sm:grid-cols-2 xl:grid-cols-3" : "space-y-3"}`}>{visible.map((space) => <article key={space.id} className="relative rounded-2xl border border-stone-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-violet-200 hover:shadow-md"><button onClick={() => open(space)} className="block w-full text-left"><div className="flex items-start gap-3"><span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl" style={{ backgroundColor: `${space.color}18`, color: space.color }}><Folder className="h-6 w-6 fill-current/20" /></span><span className="min-w-0 flex-1"><span className="block truncate text-lg font-semibold">{space.name}</span><span className="mt-1 line-clamp-2 block min-h-10 text-sm leading-5 text-stone-500">{space.description || "No description yet."}</span></span></div><span className="mt-5 flex items-center justify-between"><span className="flex -space-x-2">{space.members.slice(0,4).map((person) => <Avatar key={person.email} person={person} />)}</span><span className="text-xs text-stone-500">{space.pageCount} Pages · {relativeTime(space.updatedAt)}</span></span></button><button onClick={() => run(() => setSpaceFavorite(space.id, !space.isFavorite), space.isFavorite ? "Removed from favorites." : "Added to favorites.")} aria-label="Favorite" className="absolute right-12 top-4 rounded-lg p-2 hover:bg-violet-50"><Star className={`h-4 w-4 ${space.isFavorite ? "fill-amber-400 text-amber-400" : "text-stone-400"}`} /></button><button onClick={() => setMenu(menu === space.id ? null : space.id)} aria-label="More actions" className="absolute right-3 top-4 rounded-lg p-2 hover:bg-stone-100"><MoreHorizontal className="h-4 w-4" /></button>{menu === space.id && <div className="absolute right-3 top-14 z-20 w-48 rounded-xl border bg-white p-1.5 text-sm shadow-xl">{space.isOwner && <><Menu label="Rename / change color" onClick={() => setDialog(space)} /><Menu label="Duplicate" onClick={() => run(() => duplicateSpace(space.id), "Space duplicated.")} /></>}{space.archivedAt ? <>{space.isOwner && <Menu label="Restore" onClick={() => run(() => setSpaceArchived(space.id, false), "Space restored.")} />}{space.isOwner && <Menu danger label="Delete permanently" onClick={() => window.confirm(`Permanently delete "${space.name}" and all pages?`) && run(() => permanentlyDeleteSpace(space.id), "Space permanently deleted.")} />}</> : space.isOwner && <Menu label="Archive" onClick={() => run(() => setSpaceArchived(space.id, true), "Space archived.")} />}</div>}</article>)}{!visible.length && <div className={view === "grid" ? "sm:col-span-2 xl:col-span-3" : ""}><Empty title={search ? "No matching spaces" : filter === "archived" ? "No archived spaces" : "Create your first space"} detail={search ? "Try another search term." : "Spaces keep related pages and collaborators together."} /></div>}</section>
    {dialog && <SpaceDialog space={dialog === "create" ? null : dialog} pending={pending} onClose={() => setDialog(null)} onSubmit={(input) => dialog === "create" ? run(() => createSpace(input), "Space created.", (id) => router.push(`/spaces/${id}`)) : run(() => updateSpace(dialog.id, input), "Space updated.")} />}
  </div>;
}
function Menu({ label, onClick, danger=false }: { label: string; onClick: () => void; danger?: boolean }) { return <button onClick={onClick} className={`block w-full rounded-lg px-3 py-2 text-left hover:bg-stone-50 ${danger ? "text-rose-600" : ""}`}>{label}</button>; }
function SpaceDialog({ space, pending, onClose, onSubmit }: { space: Space | null; pending: boolean; onClose: () => void; onSubmit: (input: { name: string; description: string; color: string }) => void }) {
  const [name,setName]=useState(space?.name || ""); const [description,setDescription]=useState(space?.description || ""); const [color,setColor]=useState(space?.color || colors[0]);
  return <Modal title={space ? "Edit Space" : "Create New Space"} onClose={onClose}><form onSubmit={(event) => { event.preventDefault(); onSubmit({name,description,color}); }} className="space-y-4"><label className="block text-sm font-medium">Space Name<input autoFocus maxLength={120} value={name} onChange={(e)=>setName(e.target.value)} className={"mt-2 "+fieldClass} /></label><label className="block text-sm font-medium">Description<textarea maxLength={1000} value={description} onChange={(e)=>setDescription(e.target.value)} className="mt-2 min-h-24 w-full rounded-xl border border-stone-200 p-3 text-sm outline-none focus:border-violet-400" /></label><div><p className="text-sm font-medium">Color</p><div className="mt-2 flex gap-2">{colors.map((item)=><button type="button" aria-label={item} key={item} onClick={()=>setColor(item)} className={`h-8 w-8 rounded-full ${color===item ? "ring-2 ring-violet-500 ring-offset-2" : ""}`} style={{backgroundColor:item}} />)}</div></div><button disabled={pending} className="h-11 w-full rounded-xl bg-violet-600 font-semibold text-white disabled:opacity-50">{space ? "Save Changes" : "Create Space"}</button></form></Modal>;
}
