"use client";

import Placeholder from "@tiptap/extension-placeholder";
import StarterKit from "@tiptap/starter-kit";
import { EditorContent, useEditor } from "@tiptap/react";
import { Archive, ArrowLeft, Bold, Check, Copy, Download, FileText, Italic, Link2, List, ListOrdered, MessageSquare, MoreHorizontal, Share2, Star, Trash2 } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useRef, useState, useTransition } from "react";
import { duplicatePage, movePage, permanentlyDeletePage, recordSpaceOpen, savePage, setPageArchived, setPageFavorite } from "../../../actions";
import { templateLabels, type PageTemplate } from "@/lib/page-templates";
import { Avatar, fieldClass, Modal, relativeTime } from "../../../spaces-ui";

type PageData={id:number;spaceId:number;name:string;description:string|null;template:string;content:unknown;createdBy:string;updatedBy:string;archivedAt:string|null;createdAt:string;updatedAt:string;isFavorite:boolean};

export function PageWorkspace({page,space,editor:updatedBy,availableSpaces}:{page:PageData;space:{id:number;name:string;color:string;isOwner:boolean};editor:{name:string|null;email:string;avatarUrl:string|null}|null;availableSpaces:{id:number;name:string;archived:boolean}[]}) {
  const router=useRouter(); const [name,setName]=useState(page.name); const [description,setDescription]=useState(page.description||""); const [status,setStatus]=useState<"saved"|"saving"|"error">("saved"); const [menu,setMenu]=useState(false); const [moveOpen,setMoveOpen]=useState(false); const [message,setMessage]=useState(""); const [pending,startTransition]=useTransition(); const timer=useRef<ReturnType<typeof setTimeout>|null>(null); const nameRef=useRef(name); const descriptionRef=useRef(description); nameRef.current=name;descriptionRef.current=description;
  const tiptap=useEditor({immediatelyRender:false,extensions:[StarterKit,Placeholder.configure({placeholder:"Start writing, or press / for ideas…" })],content:page.content as object,editorProps:{attributes:{class:"notes-prose min-h-[55vh] outline-none"}},onUpdate:({editor})=>schedule(editor.getJSON())});
  function persist(content=tiptap?.getJSON()){if(!content)return;if(timer.current)clearTimeout(timer.current);setStatus("saving");savePage(page.id,{name:nameRef.current,description:descriptionRef.current,content}).then(()=>setStatus("saved")).catch(()=>setStatus("error"));}
  function schedule(content=tiptap?.getJSON()){if(!content)return;setStatus("saving");if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>persist(content),700);}
  const run=(action:()=>Promise<unknown>,success:string,after?:(value:unknown)=>void)=>startTransition(async()=>{try{const result=await action();setMessage(success);setMenu(false);after?.(result);router.refresh();}catch(error){setMessage(error instanceof Error?error.message:"Something went wrong.");}});
  useEffect(()=>{void recordSpaceOpen(space.id);return()=>{if(timer.current)clearTimeout(timer.current);persist();}},[]);
  function exportMarkdown(){const text=tiptap?.getText()||"";const blob=new Blob([`# ${name}\n\n${description?description+"\n\n":""}${text}`],{type:"text/markdown"});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=`${name.replace(/[^a-z0-9]+/gi,"-").toLowerCase()||"page"}.md`;link.click();URL.revokeObjectURL(url);}
  return <div className="min-h-screen bg-white">{message&&<button onClick={()=>setMessage("")} className="fixed bottom-5 right-5 z-[100] rounded-xl bg-stone-900 px-4 py-3 text-sm text-white">{message}</button>}
    <header className="sticky top-0 z-30 border-b border-stone-200 bg-white/95 px-4 py-3 backdrop-blur sm:px-7"><div className="mx-auto flex max-w-6xl items-center gap-3"><Link href={`/spaces/${space.id}`} onClick={()=>persist()} className="flex h-9 items-center gap-1 rounded-lg border px-2 text-xs font-medium"><ArrowLeft className="h-4 w-4"/><span className="hidden sm:inline">{space.name}</span></Link><FileText className="h-5 w-5" style={{color:space.color}}/><div className="min-w-0 flex-1"><input disabled={Boolean(page.archivedAt)} value={name} maxLength={120} onChange={(e)=>{setName(e.target.value);nameRef.current=e.target.value;schedule()}} onBlur={()=>persist()} className="w-full truncate bg-transparent font-semibold outline-none"/><p className="text-xs text-stone-400">{templateLabels[page.template as PageTemplate]||page.template}</p></div><span className={`hidden text-xs sm:flex ${status==="error"?"text-rose-600":"text-stone-400"}`}>{status==="saving"?"Saving…":status==="error"?"Save failed":<span className="flex items-center gap-1"><Check className="h-3.5 w-3.5 text-emerald-600"/>Saved</span>}</span><button onClick={()=>run(()=>setPageFavorite(page.id,!page.isFavorite),page.isFavorite?"Removed from favorites.":"Added to favorites.")} className="rounded-lg p-2"><Star className={`h-4 w-4 ${page.isFavorite?"fill-amber-400 text-amber-400":"text-stone-400"}`}/></button><button onClick={()=>setMenu(!menu)} className="rounded-lg p-2 hover:bg-stone-100"><MoreHorizontal className="h-4 w-4"/></button>{menu&&<div className="absolute right-6 top-14 w-52 rounded-xl border bg-white p-1.5 text-sm shadow-xl"><Menu icon={<Copy/>} label="Duplicate" onClick={()=>run(()=>duplicatePage(page.id),"Page duplicated.",(id)=>router.push(`/spaces/${space.id}/pages/${id}`))}/><Menu icon={<Share2/>} label="Share / collaborators" onClick={()=>router.push(`/spaces/${space.id}?share=1`)}/><Menu icon={<Link2/>} label="Move" onClick={()=>setMoveOpen(true)}/><Menu icon={<Download/>} label="Export Markdown" onClick={exportMarkdown}/>{page.archivedAt?<Menu danger icon={<Trash2/>} label="Delete permanently" onClick={()=>window.confirm(`Permanently delete "${page.name}"?`)&&run(()=>permanentlyDeletePage(page.id),"Page deleted.",()=>router.push(`/spaces/${space.id}`))}/>:<Menu icon={<Archive/>} label="Archive" onClick={()=>run(()=>setPageArchived(page.id,true),"Page archived.",()=>router.push(`/spaces/${space.id}`))}/>}</div>}</div></header>
    <main className="mx-auto grid max-w-6xl gap-6 px-4 py-7 lg:grid-cols-[minmax(0,1fr)_280px] lg:px-7"><section className="min-w-0"><textarea disabled={Boolean(page.archivedAt)} value={description} maxLength={1000} onChange={(e)=>{setDescription(e.target.value);descriptionRef.current=e.target.value;schedule()}} onBlur={()=>persist()} placeholder="Add a short page description…" className="mb-5 min-h-16 w-full resize-none rounded-xl border border-violet-100 bg-violet-50/30 p-3 text-sm outline-none focus:border-violet-300"/>{tiptap&&<><div className="sticky top-[65px] z-20 mb-6 flex flex-wrap gap-1 rounded-xl border bg-white p-2 shadow-sm"><Tool active={tiptap.isActive("bold")} onClick={()=>tiptap.chain().focus().toggleBold().run()} icon={<Bold/>}/><Tool active={tiptap.isActive("italic")} onClick={()=>tiptap.chain().focus().toggleItalic().run()} icon={<Italic/>}/><Tool active={tiptap.isActive("bulletList")} onClick={()=>tiptap.chain().focus().toggleBulletList().run()} icon={<List/>}/><Tool active={tiptap.isActive("orderedList")} onClick={()=>tiptap.chain().focus().toggleOrderedList().run()} icon={<ListOrdered/>}/></div><EditorContent editor={tiptap}/></>}</section><aside><div className="rounded-2xl border border-violet-100 bg-violet-50/35 p-5"><p className="text-xs font-semibold uppercase text-violet-600">Page Preview</p><h2 className="mt-3 text-lg font-semibold">{name}</h2><span className="mt-2 inline-flex rounded-lg bg-white px-2 py-1 text-xs font-medium text-violet-700">{templateLabels[page.template as PageTemplate]}</span><dl className="mt-5 space-y-4 text-sm"><Meta label="Space" value={space.name}/><Meta label="Comments" value="0"/><Meta label="Linked tasks" value="0"/><Meta label="Last updated" value={relativeTime(page.updatedAt)}/></dl>{updatedBy&&<div className="mt-5 flex items-center gap-2 border-t border-violet-100 pt-4"><Avatar person={updatedBy}/><div><p className="text-xs text-stone-500">Last edited by</p><p className="text-sm font-medium">{updatedBy.name||updatedBy.email}</p></div></div>}</div></aside></main>
    {moveOpen&&<Modal title="Move Page" onClose={()=>setMoveOpen(false)}><div className="space-y-2">{availableSpaces.filter((item)=>item.id!==space.id&&!item.archived).map((item)=><button key={item.id} onClick={()=>run(()=>movePage(page.id,item.id),"Page moved.",()=>router.push(`/spaces/${item.id}/pages/${page.id}`))} className="block w-full rounded-xl border p-3 text-left font-medium hover:border-violet-300">{item.name}</button>)}{!availableSpaces.some((item)=>item.id!==space.id&&!item.archived)&&<p className="text-sm text-stone-500">Create another active space before moving this page.</p>}</div></Modal>}
  </div>;
}
function Menu({icon,label,onClick,danger=false}:{icon:React.ReactElement;label:string;onClick:()=>void;danger?:boolean}){return <button onClick={onClick} className={`flex w-full items-center gap-2 rounded-lg px-3 py-2 text-left [&_svg]:h-4 [&_svg]:w-4 ${danger?"text-rose-600":"hover:bg-stone-50"}`}>{icon}{label}</button>}
function Tool({icon,onClick,active}:{icon:React.ReactElement;onClick:()=>void;active:boolean}){return <button onMouseDown={(e)=>e.preventDefault()} onClick={onClick} className={`rounded-lg p-2 [&_svg]:h-4 [&_svg]:w-4 ${active?"bg-violet-100 text-violet-700":"hover:bg-stone-100"}`}>{icon}</button>}
function Meta({label,value}:{label:string;value:string}){return <div className="flex justify-between gap-3"><dt className="text-stone-500">{label}</dt><dd className="truncate font-medium">{value}</dd></div>}
